name: Deploy Next.js site to Pages

on:
  push:
    branches: ["2025-in-react"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          cd aftrecki
          if [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
        working-directory: aftrecki # <-- Add this line to set the working directory

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
        working-directory: aftrecki # <-- Add this line to set the working directory

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: aftrecki/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('aftrecki/**/package-lock.json', 'aftrecki/**/yarn.lock') }}-${{ hashFiles('aftrecki/**.[jt]s', 'aftrecki/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('aftrecki/**/package-lock.json', 'aftrecki/**/yarn.lock') }}-
        working-directory: aftrecki # <-- Add this line to set the working directory

      - name: Install dependencies
        run: |
          cd aftrecki
          ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
        working-directory: aftrecki # <-- Add this line to set the working directory

      - name: Build with Next.js
        run: |
          cd aftrecki
          ${{ steps.detect-package-manager.outputs.runner }} next build
        working-directory: aftrecki # <-- Add this line to set the working directory

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: aftrecki/out
        working-directory: aftrecki # <-- Add this line to set the working directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        working-directory: aftrecki # <-- Add this line to set the working directory
